name: Action Delete Branch After Pull-request
on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: delete branch after pull-request
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
